Update patch set 14
Patch Set 14:

(11 comments)

You'll need to update aom/exports_com to address these errors:

17:41:53 CMakeFiles/test_aom_common.dir/test/metadata_memory_handling_test.cc.o: In function `MetadataMemoryHandlingTest_MetadataAllocation_Test::TestBody()':
17:41:53 metadata_memory_handling_test.cc:(.text+0x4e): undefined reference to `aom_metadata_alloc'
17:41:53 metadata_memory_handling_test.cc:(.text+0x166): undefined reference to `aom_metadata_free'
17:41:53 CMakeFiles/test_aom_common.dir/test/metadata_memory_handling_test.cc.o: In function `MetadataMemoryHandlingTest_MetadataArrayAllocation_Test::TestBody()':
17:41:53 metadata_memory_handling_test.cc:(.text+0x314): undefined reference to `aom_metadata_array_alloc'
17:41:53 metadata_memory_handling_test.cc:(.text+0x43a): undefined reference to `aom_metadata_alloc'
17:41:53 metadata_memory_handling_test.cc:(.text+0x459): undefined reference to `aom_metadata_alloc'
17:41:53 metadata_memory_handling_test.cc:(.text+0x46b): undefined reference to `aom_metadata_array_free'
17:41:53 CMakeFiles/test_aom_common.dir/test/metadata_memory_handling_test.cc.o: In function `MetadataMemoryHandlingTest_CopyMetadataToFrameBUffer_Test::TestBody()':
17:41:53 metadata_memory_handling_test.cc:(.text+0x623): undefined reference to `aom_metadata_array_alloc'
17:41:53 metadata_memory_handling_test.cc:(.text+0x74c): undefined reference to `aom_metadata_alloc'
17:41:53 metadata_memory_handling_test.cc:(.text+0x768): undefined reference to `aom_copy_metadata_to_frame_buffer'
17:41:53 metadata_memory_handling_test.cc:(.text+0x84f): undefined reference to `aom_remove_metadata_from_frame_buffer'
17:41:53 CMakeFiles/test_aom_common.dir/test/metadata_memory_handling_test.cc.o: In function `MetadataMemoryHandlingTest_RemoveMetadataFromImage_Test::TestBody()':
17:41:53 metadata_memory_handling_test.cc:(.text+0xa53): undefined reference to `aom_add_metadata_to_img'
17:41:53 metadata_memory_handling_test.cc:(.text+0xbe2): undefined reference to `aom_remove_metadata_from_img'
17:41:53 CMakeFiles/test_aom_common.dir/test/metadata_memory_handling_test.cc.o: In function `MetadataMemoryHandlingTest_AddMetadataToImage_Test::TestBody()':
17:41:53 metadata_memory_handling_test.cc:(.text+0xde0): undefined reference to `aom_add_metadata_to_img'
17:41:53 metadata_memory_handling_test.cc:(.text+0xf62): undefined reference to `aom_metadata_array_free'
17:41:53 collect2: error: ld returned 1 exit status

Each function triggering an undefined reference error needs a line in the file:

text func_name

Patch-set: 14
Reviewer: Gerrit User 5215 <5215@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>