Update patch set 4
Patch Set 4:

> Patch Set 3:
> 
> this one fails to build on mac, maybe you included a fix in the next one:
> 
> av1/encoder/rdopt.c:1408:59: error: use of undeclared identifier 'CONFIG_DAALA_DIST'
>     if (args->cpi->sf.use_transform_domain_distortion && !CONFIG_DAALA_DIST) {

Yeah, forgot I had a rebase to do:

https://aomedia-review.googlesource.com/c/7403/

Patch-set: 4
Label: Code-Review=0