arm: Fix building intrinsics with clang
This fixes compiler errors like these with clang (latest trunk
version):

In file included from av1/common/arm/av1_txfm_neon.c:16:
av1/common/arm/mem_neon.h:28:7: error: argument to '__builtin_neon_vld1_lane_v' must be a constant integer
      vld1_lane_u32((uint32_t *)s, vreinterpret_u32_u8(*s0), lane));
      ^                                                      ~~~~
lib/clang/7.0.0/include/arm_neon.h:8435:24: note: expanded from macro 'vld1_lane_u32'
  __ret = (uint32x2_t) __builtin_neon_vld1_lane_v(__p0, (int8x8_t)__s1, __p2, 18); \
                       ^                                                ~~~~

Convert the inline functions into defines, to allow the compiler to
see the arguments as immediate values instead of as a potential variable.

Change-Id: Ib1ae336d32512c91265c7f8ecf873cabe763c257