Update patch set 23
Patch Set 23:

> I might not have been clear earlier - tests intentionally bypass
 > the RTCD system of having a global pointer, and sending that to the
 > highest supported arch (for example, aom_sad4x4 would get
 > pointed/defined to aom_sad4x4_sse2). Instead the tests call the
 > functions directly (aom_sad4x4_sse2 in this case), but the test
 > name is prefixed with SSE2 so it can be filtered out.

Since there isn't an v128_add_8_sse2 version of v128_add_8, etc, I had to do it differently.  It doesn't make sense to have v128_add_8 as a global pointer, of course, since going through a function call would be extremely inefficient.  These functions are only intended to exist as inline functions and they are usually not instantiated Except in the tests, where they have to be instantiated, since I create function pointers to them, but all this happens implicitly.  Making explicit function wrappers to have every intrinsic instantiated would add a lot of code lines, which would have to be updated if intrinsics are added or removed.  Since the tests are so many, I put some effort into making the code doing this as small as possible.

SSE4.1 intrinsics are used in simd_test_sse4.cc, SSSE3 intrinsics in simd_test_ssse3.cc, etc.  For instance, if you make a change in the SSE4.1 version of v128_dotp_s16 to make it incorrect, you will get an error like:

Error: mismatch for v128_dotp_s16(0x10df837a9043deaafedfbaf5c461be20, 0xccbadb03cfebc3471fc23f3bf04df3f2) -> 0x00000000014403fe (simd), 0x0000000021125afd (ref)

but the SSE2 and SSSE3 tests will pass.

I found out that tests for v64_dotp_s16 and v128_dotp_s16 were missing, so those were added in the most recent upload.

Patch-set: 23
Label: Code-Review=0