highbd_sad_sse2.asm: fix xmm count for sad_skip
propagate the xmm argument to the function definitions rather than the
hard coded '7'. some cases use xmm7.

fixes failures on windows of the form:
[ RUN      ] SSE2/SADSkipTest.MaxRef/27
test/register_state_check.h(70): error: Expected equality of these values:
  *xmm_pre
    Which is: 16-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
  *xmm_post
    Which is: 16-byte object <FF-00 FF-00 FF-00 FF-00 FF-00 FF-00 FF-00 FF-00>
xmm7 has been modified!

Bug: aomedia:3175
Change-Id: I10d447de2b4095ee7444f62bba04629bd0abfc02