Update patch set 4
Patch Set 4:

this fails to link under high-bitdepth:

./libaom.a(aom_dsp_rtcd.c.o): In function `setup_rtcd_internal':
./aom_dsp_rtcd.h:2614: undefined reference to `aom_highbd_idct8x8_64_add_c'

I'll send a change to clear the remaining references

Patch-set: 4
CC: Gerrit User 5020 <5020@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>