aom_set_error: aom_internal_error without longjmp
Add the aom_set_error() function, which is the same as
aom_internal_error() but doesn't call longjmp().

We often assume aom_internal_error() calls longjmp(), but some code
calls aom_internal_error() just to record the error code and error
message. It is clearer to use a different function for this use case.

Use aom_set_error() in av1_receive_raw_frame() and apply_denoise_2d().

Change-Id: I74b1b4c0195298110eea6db725aa25a7e13821d0