sanitizers.cmake: fix link errors for 32-bit ubsan
undefined reference to `__mulodi4'
due to missing rtlib. avoids needing to add extra flags with
CMAKE_EXE_LINKER_FLAGS

Change-Id: I473291deef4e93c1bbbac0ac32606f8cf3925ea9