Update patch set 3
Patch Set 3:

Patch#5 does not work because the way the macro is used: 
1>  highbd_intrapred_avx2.c
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(71): error C2059: syntax error: '{'
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(71): error C2065: 'y': undeclared identifier
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(71): error C2440: 'function': cannot convert from 'int' to '__m128i'
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(71): warning C4024: '_mm_insert_epi16': different types for formal and actual parameter 1
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(71): error C2440: '=': cannot convert from '__m128i' to 'int'
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(71): warning C4024: '_mm256_insertf128_si256': different types for formal and actual parameter 2
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(71): error C2059: syntax error: ')'
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(72): error C2065: 'x1': undeclared identifier
1>C:\webm\aom\aom_dsp\x86\highbd_intrapred_avx2.c(72): warning C4133: 'function': incompatible type

Patch-set: 3