highbitdepth + loop restoration: fix build on x86 32 bit
When the functions were added in
https://aomedia-review.googlesource.com/6545 they were not restricted to
x86_64 builds.

Fixes "undefined reference to
`aom_highbd_convolve8_add_src_sse2'" for --target=x86-linux-gcc

Also remove SSE2 specializations from
`aom_highbd_convolve8_add_src[_horiz/_vert]`, since those functions
don't actually have SSE2 versions (this was left in by accident
in the original patch).

Change-Id: I9f7d0c11b58b6f5a0e6a1fdaed0f92175bdeab34