Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Ah, thanks: You need to add analyzer to CONFIG_LIST in configure in
>  > the above patch. That'll cause the system to attempt to build it.
> 
> Tom, I have done this before and gotten the following error:
> 
> make[1]: Circular examples/analyzer.cc.o <- examples/analyzer.cc dependency dropped.
> 
> Would you mind checking these patches out locally and trying?
> 

I'm seeing the same here. Something odd, perhaps a gap in the existing build system. There are no existing example targets that are C++. A rule for cc files isn't present, or something similar. You can at least get the build system to start tying to build the analyzer by dropping this into examples.mk:

  EXAMPLES-$(CONFIG_DECODERS)        += analyzer.c
  analyzer.GUID                       = 83827a8c-e3c3-4b19-8832-0cfc206c4496
  analyzer.SRCS                      += ivfdec.h ivfdec.c examples/analyzer.cc

analyzer.c is an empty file in aom/examples on my system. The wx-config stuff either isn't working on my system, or I've applied patches incorrectly:

tomfinegan@tomfinegan-macpro:~/webm/_builds/aom/configure_analyzer $ make
make[1]: Nothing to be done for `all'.
    [LD] aomdec
    [LD] aomenc
    [CXX] examples/analyzer.cc.o
../../../aom/examples/analyzer.cc:1:10: fatal error: 'wx/wx.h' file not found
#include <wx/wx.h>
         ^
1 error generated.
make[1]: *** [examples/analyzer.cc.o] Error 1
make: *** [.DEFAULT] Error 2

> Also, how are the aomenc and aomdec binaries added?  They are not part of CONFIG_LIST.

This is how CONFIG_ANALYZER gets set. Because aomdec and aomenc are not behind flags specific to them they don't need entries in CONFIG_LIST-- they obey CONFIG_DECODERS and CONFIG_ENCODERS directly.

Patch-set: 5