Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> -DENABLE_SSSE3=NO seems to generate the expected config.
> doesn't build ><. might be a pre-existing condition, configure seems to work.
> 
> cmake .. -DENABLE_SSSE3=NO
> ...
> av1_rtcd.c:(.text+0x5a3): undefined reference to `copy_rect8_8bit_to_16bit_sse4_1'

Sorry: Too much multitasking. I thought I actually ran a couple configs with SSE's turned off, but I most certainly did not based on this behavior.

I missed that in addition to the HAVE_$flavor stuff that --disable-$flavor needs to be passed to rtcd.pl when turning something off. Should be good now.

Patch-set: 2