Update patch set 2
Patch Set 2:

If "-DCONFIG_DIST_8X8=0" is used with cmake,

av1/encoder/rdopt.c:3520:35: error: unused variable 'pd' [-Werror,-Wunused-variable]
  struct macroblockd_plane *const pd = &xd->plane[0];

Patch-set: 2
Reviewer: Gerrit User 5035 <5035@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>