Set the error string for aom_codec_control()
Set the error string for aom_codec_control() to "Invalid control ID" if
the ctrl_id argument is invalid.

Suppose we manually modified apps/aomenc.c so that we incorrectly used
the control ID 6789 for the --cpu-used command-line argument. Here are
the error messages of the command

  aomenc --cpu-used=6 niklas_1280_720_30.y4m -o output.yuv

Before:
  Error: Tried to set control 6789 = 6
  Failed to control codec: Unspecified internal error
After:
  Error: Tried to set control 6789 = 6
  Failed to control codec: Unspecified internal error
      Invalid control ID

Change-Id: I3524f734bc177af6f33a2c66555957522ca07353