Update patch set 6
Patch Set 6:

This breaks build:
/aom/aom/av1/encoder/encoder.c:5105:28: error: ‘AV1_COMP {aka struct AV1_COMP}’ has no member named ‘interp_filter_selected’
       ref_total[ref] += cpi->interp_filter_selected[ref][ifilter];

Patch-set: 6
CC: Gerrit User 5187 <5187@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>