Remove const from fc param of av1_fill_mv_costs
The fc parameter of av1_fill_mv_costs is declared as
    const FRAME_CONTEXT *const fc
in the rd.h, but in the definition of this function in rd.c, the fc
parameter is declared as
    const FRAME_CONTEXT *fc

Visual C++ requires the types in the declaration and definition to
match exactly. Remove the second 'const' in the declaration to fix the
following Visual C++ compilation error:
    C:\src\buildbot\test-libvpx\tests_aom\opFUi0b0g8\av1\encoder\rd.c(584):
    warning C4028: formal parameter 1 different from declaration

Note: The code was added in commit 8d27341b50bdce48b2e694aa8f78e8633c99f873
https://aomedia-review.googlesource.com/c/aom/+/95301

Change-Id: I4184a7f9736b55f40457a3deea18333064da5e19