Update patch set 4
Patch Set 4: Code-Review-1

(1 comment)

This breaks the mac shared build with CONFIG_INSPECTION=0 since these symbols exist only when CONFIG_INSPECTION=1:

ifd_init
ifd_inspect

Errors:

[ 83%] Linking C shared library libaom.dylib
Undefined symbols for architecture x86_64:
  "_ifd_init", referenced from:
     -exported_symbol[s_list] command line option
  "_ifd_inspect", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libaom.0.dylib] Error 1
make[1]: *** [CMakeFiles/aom.dir/all] Error 2
make: *** [all] Error 2

Linux appears OK. Haven't tried Windows. 

The CMake script handling the exports will need updates before this can be landed. The immediately obvious fix is to create an exports_ident file and list the symbols there, and then update the CMake exports script to append it to exports_dec when CONFIG_INSPECTION == 1.

Patch-set: 4
Reviewer: Gerrit User 5215 <5215@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>
Label: Code-Review=-1