Update patch set 2
Patch Set 2: Code-Review-1

While this patch does fix the build error related to missing field compound_type_cdf from the FRAME_CONTEXT struct, I am still getting a different build error when I apply this patch and compile with:

./configure --enable-experimental --disable-ext_inter

    [CC] av1/common/entropy.c.o
../av1/common/entropy.c: In function ‘av1_average_tile_inter_cdfs’:
../av1/common/entropy.c:5616:45: error: ‘FRAME_CONTEXT’ has no member named ‘interintra_mode_cdf’
     cdf_ptr[i] = (aom_cdf_prob *)&ec_ctxs[i]->cname;        \
                                             ^
../av1/common/entropy.c:5725:3: note: in expansion of macro ‘AVERAGE_TILE_CDFS’
   AVERAGE_TILE_CDFS(interintra_mode_cdf)
   ^
../av1/common/entropy.c:5617:35: error: ‘FRAME_CONTEXT’ has no member named ‘interintra_mode_cdf’
   fc_cdf_ptr = (aom_cdf_prob *)&fc->cname;                  \
                                   ^
../av1/common/entropy.c:5725:3: note: in expansion of macro ‘AVERAGE_TILE_CDFS’
   AVERAGE_TILE_CDFS(interintra_mode_cdf)
   ^
../av1/common/entropy.c:5618:28: error: ‘FRAME_CONTEXT’ has no member named ‘interintra_mode_cdf’
   cdf_size = (int)sizeof(fc->cname) / sizeof(aom_cdf_prob); \
                            ^
../av1/common/entropy.c:5725:3: note: in expansion of macro ‘AVERAGE_TILE_CDFS’
   AVERAGE_TILE_CDFS(interintra_mode_cdf)
   ^
Makefile:162: recipe for target 'av1/common/entropy.c.o' failed
make[1]: *** [av1/common/entropy.c.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:17: recipe for target '.DEFAULT' failed
make: *** [.DEFAULT] Error 2

Patch-set: 2
Reviewer: Gerrit User 5046 <5046@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>
Label: Code-Review=-1