Update patch set 2
Patch Set 2: Verified+1

This patch fixes this compile error:
/Users/tomfinegan/_werk/aom/av1/decoder/obu.c:188:38: error: no member named 'enhancement_layers_cnt' in 'struct AV1Common'
      operating_point >= pbi->common.enhancement_layers_cnt)

Setting verified manually because this may be blocking people because the build is broken. Can revert or adjust later.

Patch-set: 2
Reviewer: Gerrit User 5215 <5215@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>
Label: Verified=+1