Update patch set 3
Patch Set 3:

The following is the Jenkins test result for this patch:

09:04:39 /var/jenkins/workspace/libaom__abi_check/default/aom/av1/decoder/decodeframe.c: In function ‘row_mt_worker_hook’:
09:04:39 /var/jenkins/workspace/libaom__abi_check/default/aom/av1/decoder/decodeframe.c:3096:34: warning: passing argument 2 of ‘av1_zero_above_context’ makes pointer from integer without a cast [-Wint-conversion]
09:04:39        av1_zero_above_context(cm, tile_info.mi_col_start, tile_info.mi_col_end,
09:04:39                                   ^~~~~~~~~
09:04:39 In file included from /var/jenkins/workspace/libaom__abi_check/default/aom/av1/common/cdef.h:24:0,
09:04:39                  from /var/jenkins/workspace/libaom__abi_check/default/aom/av1/decoder/decodeframe.c:37:
09:04:39 /var/jenkins/workspace/libaom__abi_check/default/aom/av1/common/onyxc_int.h:1068:20: note: expected ‘const MACROBLOCKD * {aka const struct macroblockd *}’ but argument is of type ‘int’
09:04:39  static INLINE void av1_zero_above_context(AV1_COMMON *const cm, const MACROBLOCKD *xd,
09:04:39                     ^~~~~~~~~~~~~~~~~~~~~~
09:04:39 /var/jenkins/workspace/libaom__abi_check/default/aom/av1/decoder/decodeframe.c:3096:7: error: too few arguments to function ‘av1_zero_above_context’
09:04:39        av1_zero_above_context(cm, tile_info.mi_col_start, tile_info.mi_col_end,
09:04:39        ^~~~~~~~~~~~~~~~~~~~~~
09:04:39 In file included from /var/jenkins/workspace/libaom__abi_check/default/aom/av1/common/cdef.h:24:0,
09:04:39                  from /var/jenkins/workspace/libaom__abi_check/default/aom/av1/decoder/decodeframe.c:37:
09:04:39 /var/jenkins/workspace/libaom__abi_check/default/aom/av1/common/onyxc_int.h:1068:20: note: declared here
09:04:39  static INLINE void av1_zero_above_context(AV1_COMMON *const cm, const MACROBLOCKD *xd,
09:04:39                     ^~~~~~~~~~~~~~~~~~~~~~
09:04:39 CMakeFiles/aom_av1_decoder.dir/build.make:86: recipe for target 'CMakeFiles/aom_av1_decoder.dir/av1/decoder/decodeframe.c.o' failed
09:04:39 make[2]: *** [CMakeFiles/aom_av1_decoder.dir/av1/decoder/decodeframe.c.o] Error 1

Since this is blocking everybody, I will check this in.

Patch-set: 3
Reviewer: Gerrit User 5185 <5185@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>