Update patch set 3
Patch Set 3:

Failure reproduces locally. May be an auto-merge error?
commit b4c616444c470e6f7f2cd7d4476164e82cc6d2f6
$ cmake ../libaom
$ make
<...>
/usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/highbd_fwd_txfm_sse4.c: In function ‘av1_fwd_txfm2d_16x8_sse4_1’:
/usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/highbd_fwd_txfm_sse4.c:1750:5: error: too few arguments to function ‘av1_round_shift_rect_array_32_sse4_1’
     av1_round_shift_rect_array_32_sse4_1(in, in, 16, -shift[2]);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/av1_txfm1d_sse4.h:17:0,
                 from /usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/highbd_fwd_txfm_sse4.c:20:
/usr/local/google/home/johannkoenig/libaom/av1/common/x86/av1_txfm_sse4.h:45:20: note: declared here
 static INLINE void av1_round_shift_rect_array_32_sse4_1(__m128i *input,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/highbd_fwd_txfm_sse4.c: In function ‘av1_fwd_txfm2d_8x16_sse4_1’:
/usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/highbd_fwd_txfm_sse4.c:1778:5: error: too few arguments to function ‘av1_round_shift_rect_array_32_sse4_1’
     av1_round_shift_rect_array_32_sse4_1(in, in, 16, -shift[2]);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/av1_txfm1d_sse4.h:17:0,
                 from /usr/local/google/home/johannkoenig/libaom/av1/encoder/x86/highbd_fwd_txfm_sse4.c:20:
/usr/local/google/home/johannkoenig/libaom/av1/common/x86/av1_txfm_sse4.h:45:20: note: declared here
 static INLINE void av1_round_shift_rect_array_32_sse4_1(__m128i *input,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/aom_av1_encoder_sse4_intrinsics.dir/build.make:182: recipe for target 'CMakeFiles/aom_av1_encoder_sse4_intrinsics.dir/av1/encoder/x86/highbd_fwd_txfm_sse4.c.o' failed
make[2]: *** [CMakeFiles/aom_av1_encoder_sse4_intrinsics.dir/av1/encoder/x86/highbd_fwd_txfm_sse4.c.o] Error 1

Patch-set: 3