Update patch set 6
Patch Set 6:

error message is like the below for armv8-linux-gcc/config/shared-no-static. but I don't understand why:

04:08:55     [LD] aomenc
04:08:55 aomenc.c.o: In function `main':
04:08:55 aomenc.c:(.text.startup+0x2994): undefined reference to `reconfile_name'
04:08:55 aomenc.c:(.text.startup+0x29a0): undefined reference to `reconfile_name'
04:08:55 collect2: error: ld returned 1 exit status
04:08:55 ../aom/examples.mk:299: recipe for target 'aomenc' failed
04:08:55 make[1]: *** [aomenc] Error 1
04:08:55 Makefile:17: recipe for target '.DEFAULT' failed
04:08:55 make: *** [.DEFAULT] Error 2
04:08:55 + cleanup
04:08:55 + cd /var/jenkins/workspace/libaom__compile_options/arch/armv8-linux-gcc/config/shared-no-static
04:08:55 + find build -name *.[ao]
04:08:55 + xargs rm -f
04:08:55 Build step 'Execute shell' marked build as failure
04:08:55 [WARNINGS] Skipping publisher since build result is FAILURE
04:08:55 Skipped archiving because build is not successful
04:08:55 [WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
04:08:55 Finished: FAILURE

Patch-set: 6
Reviewer: Gerrit User 5326 <5326@e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0>